service: bankinginsights
# app and org for use with dashboard.serverless.com
app: banking-insights
org: epsilonalpha

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

custom:
  name: banking-insights
  cognitoUserPoolName: ${self:custom.name}-${self:provider.stage}-user-pool
  cognitoUserPoolClientName: ${self:custom.name}-${self:provider.stage}-user-pool-client
  cognitoIdentityPoolName: ${self:custom.name}-${self:provider.stage}-identity-pool
  cognitoAuthRoleName: ${self:custom.name}-${self:provider.stage}-auth-role
  cognitoUnAuthRoleName: ${self:custom.name}-${self:provider.stage}-unAuth-role
  websiteBucketName: ${self:custom.name}-${self:provider.stage}-elroy-antao

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2

# you can add packaging information here
package:
  exclude: # Specify the directories and files which should be excluded in the deployment package
    - .git/**
    - node_modules/**
    - src/**
    - public/**
    - build/**

functions:
  GetTransactions:
    handler: server/transactions.getTx
    events:
      - http:
          path: transactions
          method: get
          cors: true
          authorizer: aws_iam

resources:
  - ${file(server/resources/cognito-user-pool.yml)}
  - ${file(server/resources/cognito-identity-pool.yml)}
  - ${file(server/resources/api-gateway-errors.yml)}
  - ${file(server/resources/s3-bucket-website.yml)}