Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.cognitoUserPoolName}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:custom.cognitoUserPoolClientName}
      GenerateSecret: false
      UserPoolId:
        Ref: CognitoUserPool
Outputs:
  CognitoUserPoolId:
    Description: 'Cognito User Pool Id'
    Value:
      Ref: CognitoUserPool
  CognitoUserPoolClientId:
    Description: 'Cognito User Pool Client Id'
    Value:
      Ref: CognitoUserPoolClient