Resources:
  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.transactionTableName}
      AttributeDefinitions:
        - AttributeName: customerId
          AttributeType: S
        - AttributeName: transactionId
          AttributeType: S
      KeySchema:
        - AttributeName: customerId
          KeyType: HASH
        - AttributeName: transactionId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST